name : GitHub LP
on : 
  workflow_dispatch :
    inputs:
      jobs_to_run:
        description: 'Jobs to run'
        required: true
        default: 'build,test,deploy-qa,deploy-prod'
  schedule:   
    - cron: '0 8 * * 1' 
  push :
    branches :
      - lab9-lp
    paths-ignore:
      - 'docs/**'
  pull_request :
    branches :
      - lab9-lp
    paths-ignore:
      - 'docs/**'
    
  
permissions:
  issues: write
  contents: read
  pull-requests: write

env: 
  BUILD_ARTIFACT_NAME: "package"
  APP_LOCATION: "dist"
  OUTPUT_LOCATION: "build" 

jobs :
    build :
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
        - name: dependancies
          run: npm install #faire avec une action github ?
        - name: Application build
          run: npm run build 
        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
            name: lab9-artifact
            path: |
                dist
                !dist/**/*.md

    test:
      #allow to specify which job you want to run when manually run
      if: ${{ github.event_name != 'workflow_dispatch' || contains(github.event.inputs.jobs_to_run, 'test') }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20'
            
        - name: Install dependencies
          run: npm install
        
        - name: Run linter and static type checker
          run: npm run lint && npm run type-check
        
        - name: Run unit tests
          run: npm test

    deploy-qa:
      needs: build
      if: contains(github.event.inputs.jobs_to_run, 'deploy-qa')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: actions/download-artifact@v4
          with:
            name: lab9-artifact
            path: dist
        - name: Deploy to QA
          uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
          with :
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            app_location: ${{ env.APP_LOCATION }}
            output_location: ${{ env.OUTPUT_LOCATION }}
  
    deploy-prod :
      needs : deploy-qa
      if: contains(github.event.inputs.jobs_to_run, 'deploy-prod')
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: actions/download-artifact@v4
          with:
            name: lab9-artifact
            path: dist
        - name: Deploy to QA
          uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
          with :
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            app_location: ${{ env.APP_LOCATION }}
            output_location: ${{ env.OUTPUT_LOCATION }}

    manage-retention:
      runs-on: ubuntu-latest
      steps:
        - name: Vérifier la branche
          run: echo "La branche modifiée est ${{ github.ref }}"
        - name: Déterminer la durée de rétention
          id: retention-duration
          run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "::set-output name=duration::7 days"
            else
              echo "::set-output name=duration::1 day"
            fi
            echo "La durée de rétention est ${{ steps.retention-duration.outputs.duration }}"
            

