name : GitHub LP
on : 
    push :
        branches :
            -lab9-lp

jobs :
    build :
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: dependancies
              run: npm install 
            - name: Application build
              run: npm run build 
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-without-markdown
                path: |
                    dist
                    !dist/**/*.md